"""
generate_fish.py

Reads tools/fish_pool.csv (generated by notebooks/generate_fish.ipynb) and writes
fish_data.json to project/data/.

Usage (from repo root):
    python tools/generate_fish.py
"""

import csv
import json
import os

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
INPUT_CSV   = os.path.join(SCRIPT_DIR, "fish_pool.csv")
OUTPUT_JSON = os.path.normpath(os.path.join(SCRIPT_DIR, "..", "project", "data", "fish_data.json"))


def main():
    fish_list = []

    with open(INPUT_CSV, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            fish_list.append({
                "id":                     int(row["id"]),
                "species":                row["species"].strip(),
                "length":                 float(row["length"]),
                "weight":                 float(row["weight"]),
                "movement_tick_interval": float(row["movement_tick_interval"]),
                "bite_check_interval":    float(row["bite_check_interval"]),
                "is_trophy":              row["is_trophy"].strip().lower() == "true",
                "trophy_name":            row["trophy_name"].strip() or None,
                "trophy_title":           row["trophy_title"].strip() or None,
                "notes":                  row["notes"].strip(),
            })

    os.makedirs(os.path.dirname(OUTPUT_JSON), exist_ok=True)

    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(fish_list, f, indent=2)

    standard = sum(1 for f in fish_list if not f["is_trophy"])
    trophies = sum(1 for f in fish_list if f["is_trophy"])
    print(f"{len(fish_list)} fish written ({standard} standard, {trophies} trophy) -> {OUTPUT_JSON}")


if __name__ == "__main__":
    main()
